#!/bin/bash

#$ -cwd
#$ -t 1-5

# First element not used since SGE_TASK_ID-s start from 1.
# -ext is for the extension. 0 = base model (default) 1 = superspreaders 2 = domovi
# -extpop is number of the third (extra) population (relevant only for extension 1 and 2)


# local execution example : python crit_bound_grid.py -np 4 -mu 5 -k 2 -ext 2 -extpop 10000 1 2 3 4
# cluster_size=(-1 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 20 25 30 35 40 45 50 100 200 500 1000 5000 10000)
# cluster_size=(-1 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16)
cluster_size=(-1 2 4 6 8 10)

#superspreaderi
#python crit_bound_grid.py -mu 5 -k 2.5 -ext 1 -extpop 100 ${cluster_size[$SGE_TASK_ID]}

python crit_bound_grid.py -mu 5 -k 2.5 -ext 1 -extpop 1000 ${cluster_size[$SGE_TASK_ID]}

python crit_bound_grid.py -mu 5 -k 2.5 -ext 1 -extpop 10000 ${cluster_size[$SGE_TASK_ID]}

python crit_bound_grid.py -mu 5 -k 2.5 -ext 1 -extpop 100000 ${cluster_size[$SGE_TASK_ID]}

#domovi
#python crit_bound_grid.py -mu 5 -k 2.5 -ext 2 -extpop 100 ${cluster_size[$SGE_TASK_ID]}

#python crit_bound_grid.py -mu 5 -k 2.5 -ext 2 -extpop 1000 ${cluster_size[$SGE_TASK_ID]}

#python crit_bound_grid.py -mu 5 -k 2.5 -ext 2 -extpop 10000 ${cluster_size[$SGE_TASK_ID]}

#python crit_bound_grid.py -mu 5 -k 2.5 -ext 2 -extpop 100000 ${cluster_size[$SGE_TASK_ID]}
